// C4D-DialogResource
DIALOG DLG_TELEGRAMBOT
{


  GROUP GRP_ALL
  {
    SCALE_V; SCALE_H;
    BORDERSIZE 4, 4, 4, 4;
    COLUMNS 2;
    SPACE 4, 4;
    GROUP GRP_TEXT
    {
      NAME IDS_TEXT; ALIGN_TOP;CENTER_V; SCALE_H;
      BORDERSIZE 6, 8, 6, 8;
      BORDERSTYLE BORDER_IN;
      ROWS 1;
      SPACE 4, 4;

      EDITTEXT PASSWORD { NAME IDS_TEXT3; ALIGN_BOTTOM; ALIGN_RIGHT; SIZE 100, 10;}
      BUTTON BTN_ENTER { NAME IDS_BUTTON1; ALIGN_BOTTOM; ALIGN_RIGHT; SIZE 50, 10;}


    }
    GROUP GRP_CONTROL
    {
      NAME IDS_CONTROL; ALIGN_TOP;ALIGN_LEFT; CENTER_V; SCALE_H;
      BORDERSIZE 6, 8, 6, 8;
      BORDERSTYLE BORDER_IN;
      ROWS 3;
      SPACE 4, 4;


      BUTTON BTN_OPENBR { NAME IDS_BUTTON2; ALIGN_BOTTOM; ALIGN_RIGHT; SIZE 125, 10;}

      BUTTON BTN_SYNCH { NAME IDS_BUTTON4; ALIGN_BOTTOM; ALIGN_RIGHT; SIZE 125, 10;}


    }



      }
  }

